output "worker_node_iam_role" {
  value = module.eks_cluster.worker_node_iam_role
}

output "cluster_id" {
  value = module.eks_cluster.cluster_id
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks_cluster.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks_cluster.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks_cluster.kubectl_config
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks_cluster.config_map_aws_auth
}

output "ecr_repository_url" {
  description = "The URL to the ECR repository"
  value       = module.eks_cluster.ecr_repository_url
}

output "ecr_access_id" {
  description = "AWS Access Id for the IAM user who can upload Docker images to the ECR repo"
  value       = module.eks_cluster.ecr_access_id
}

output "ecr_secret_access_key" {
  description = "AWS Secret Access Key for the IAM user who can upload Docker images to the ECR repo"
  value       = module.eks_cluster.ecr_secret_access_key
}
