apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices
  name: service-3-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: service-3
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: service-3
    spec:
      containers:
        - image: ppanchal97/service3
          imagePullPolicy: Always
          name: service-3
          ports:
            - containerPort: 8000