apiVersion: v1
kind: Service
metadata:
  namespace: microservices
  name: service-3
spec:
  ports:
    - port: 80
      targetPort: 8000
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: service-3