---
apiVersion: v1
kind: Namespace
metadata:
  name: microservices
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: microservices
  name: payments-service-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: payments-service
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: payments-service
    spec:
      containers:
        - image: ppanchal97/paymentsservice
          imagePullPolicy: Always
          name: payments-service
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: microservices
  name: payments-service
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: payments-service
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: microservices
  name: ingress-payments-service
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  rules:
    - http:
        paths:
          - path: /*
            backend:
              serviceName: service-payments-service
              servicePort: 80
